package com.mc.mapper;

import com.mc.model.QrtzCronTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QrtzCronTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int insert(QrtzCronTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    QrtzCronTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    List<QrtzCronTriggers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int updateByPrimaryKey(QrtzCronTriggers record);
}