package com.mc.mapper;

import com.mc.model.QrtzSchedulerState;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QrtzSchedulerStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("instanceName") String instanceName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int insert(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    QrtzSchedulerState selectByPrimaryKey(@Param("schedName") String schedName, @Param("instanceName") String instanceName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    List<QrtzSchedulerState> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int updateByPrimaryKey(QrtzSchedulerState record);
}