package com.mc.mapper;

import com.mc.model.QrtzSimpropTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QrtzSimpropTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int insert(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    QrtzSimpropTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    List<QrtzSimpropTriggers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int updateByPrimaryKey(QrtzSimpropTriggers record);
}