package com.mc.mapper;

import com.mc.model.QrtzLocks;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QrtzLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("lockName") String lockName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int insert(QrtzLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    List<QrtzLocks> selectAll();
}