package com.mc.mapper;

import com.mc.model.QrtzPausedTriggerGrps;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QrtzPausedTriggerGrpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    int insert(QrtzPausedTriggerGrps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    List<QrtzPausedTriggerGrps> selectAll();
}