package com.mc.mapper;

import com.mc.model.TAccInfo;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TAccInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_info
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    int deleteByPrimaryKey(Integer taiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_info
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    int insert(TAccInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_info
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    TAccInfo selectByPrimaryKey(Integer taiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_info
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    List<TAccInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_info
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    int updateByPrimaryKey(TAccInfo record);
}