package com.mc.model;

public class QrtzJobDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String jobClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String isDurable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String isUpdateData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private byte[] jobData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.SCHED_NAME
     *
     * @return the value of qrtz_job_details.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.SCHED_NAME
     *
     * @param schedName the value for qrtz_job_details.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_NAME
     *
     * @return the value of qrtz_job_details.JOB_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_NAME
     *
     * @param jobName the value for qrtz_job_details.JOB_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @return the value of qrtz_job_details.JOB_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_job_details.JOB_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @return the value of qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @param description the value for qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @return the value of qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @param jobClassName the value for qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @return the value of qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @param isDurable the value for qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @return the value of qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @return the value of qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getIsUpdateData() {
        return isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @param isUpdateData the value for qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setIsUpdateData(String isUpdateData) {
        this.isUpdateData = isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_DATA
     *
     * @return the value of qrtz_job_details.JOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_DATA
     *
     * @param jobData the value for qrtz_job_details.JOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}