package com.mc.model;

public class QrtzSimpleTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Long repeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Long repeatInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Long timesTriggered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @return the value of qrtz_simple_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_simple_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @return the value of qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Long getRepeatCount() {
        return repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @param repeatCount the value for qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setRepeatCount(Long repeatCount) {
        this.repeatCount = repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @return the value of qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Long getRepeatInterval() {
        return repeatInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @param repeatInterval the value for qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setRepeatInterval(Long repeatInterval) {
        this.repeatInterval = repeatInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @return the value of qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Long getTimesTriggered() {
        return timesTriggered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @param timesTriggered the value for qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTimesTriggered(Long timesTriggered) {
        this.timesTriggered = timesTriggered;
    }
}