package com.mc.model;

public class QrtzSchedulerState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Long checkinInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @return the value of qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @param schedName the value for qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @return the value of qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @return the value of qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @return the value of qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}