package com.mc.model;

public class QrtzBlobTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_blob_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_blob_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_blob_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_blob_triggers.BLOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private byte[] blobData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_blob_triggers.SCHED_NAME
     *
     * @return the value of qrtz_blob_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_blob_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_blob_triggers.SCHED_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_blob_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_blob_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_blob_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_blob_triggers.TRIGGER_NAME
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_blob_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_blob_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_blob_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_blob_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_blob_triggers.BLOB_DATA
     *
     * @return the value of qrtz_blob_triggers.BLOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public byte[] getBlobData() {
        return blobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_blob_triggers.BLOB_DATA
     *
     * @param blobData the value for qrtz_blob_triggers.BLOB_DATA
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setBlobData(byte[] blobData) {
        this.blobData = blobData;
    }
}