package com.mc.model;

import java.util.Date;

public class TAccInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private Integer taiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_user_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private Integer taiUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_username
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_password
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_email
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_phone
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_rel_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_prompt_question
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiPromptQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_purpose
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_time_level
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiTimeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_acc_status
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiAccStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_work_type
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiWorkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_company
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_url
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_create_user
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_create_time
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private Date taiCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acc_info.tai_remark
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    private String taiRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_id
     *
     * @return the value of t_acc_info.tai_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public Integer getTaiId() {
        return taiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_id
     *
     * @param taiId the value for t_acc_info.tai_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiId(Integer taiId) {
        this.taiId = taiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_user_id
     *
     * @return the value of t_acc_info.tai_user_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public Integer getTaiUserId() {
        return taiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_user_id
     *
     * @param taiUserId the value for t_acc_info.tai_user_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiUserId(Integer taiUserId) {
        this.taiUserId = taiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_username
     *
     * @return the value of t_acc_info.tai_username
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiUsername() {
        return taiUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_username
     *
     * @param taiUsername the value for t_acc_info.tai_username
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiUsername(String taiUsername) {
        this.taiUsername = taiUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_password
     *
     * @return the value of t_acc_info.tai_password
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiPassword() {
        return taiPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_password
     *
     * @param taiPassword the value for t_acc_info.tai_password
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiPassword(String taiPassword) {
        this.taiPassword = taiPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_email
     *
     * @return the value of t_acc_info.tai_email
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiEmail() {
        return taiEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_email
     *
     * @param taiEmail the value for t_acc_info.tai_email
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiEmail(String taiEmail) {
        this.taiEmail = taiEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_phone
     *
     * @return the value of t_acc_info.tai_phone
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiPhone() {
        return taiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_phone
     *
     * @param taiPhone the value for t_acc_info.tai_phone
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiPhone(String taiPhone) {
        this.taiPhone = taiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_rel_id
     *
     * @return the value of t_acc_info.tai_rel_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiRelId() {
        return taiRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_rel_id
     *
     * @param taiRelId the value for t_acc_info.tai_rel_id
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiRelId(String taiRelId) {
        this.taiRelId = taiRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_prompt_question
     *
     * @return the value of t_acc_info.tai_prompt_question
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiPromptQuestion() {
        return taiPromptQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_prompt_question
     *
     * @param taiPromptQuestion the value for t_acc_info.tai_prompt_question
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiPromptQuestion(String taiPromptQuestion) {
        this.taiPromptQuestion = taiPromptQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_purpose
     *
     * @return the value of t_acc_info.tai_purpose
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiPurpose() {
        return taiPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_purpose
     *
     * @param taiPurpose the value for t_acc_info.tai_purpose
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiPurpose(String taiPurpose) {
        this.taiPurpose = taiPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_time_level
     *
     * @return the value of t_acc_info.tai_time_level
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiTimeLevel() {
        return taiTimeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_time_level
     *
     * @param taiTimeLevel the value for t_acc_info.tai_time_level
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiTimeLevel(String taiTimeLevel) {
        this.taiTimeLevel = taiTimeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_acc_status
     *
     * @return the value of t_acc_info.tai_acc_status
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiAccStatus() {
        return taiAccStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_acc_status
     *
     * @param taiAccStatus the value for t_acc_info.tai_acc_status
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiAccStatus(String taiAccStatus) {
        this.taiAccStatus = taiAccStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_work_type
     *
     * @return the value of t_acc_info.tai_work_type
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiWorkType() {
        return taiWorkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_work_type
     *
     * @param taiWorkType the value for t_acc_info.tai_work_type
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiWorkType(String taiWorkType) {
        this.taiWorkType = taiWorkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_company
     *
     * @return the value of t_acc_info.tai_company
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiCompany() {
        return taiCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_company
     *
     * @param taiCompany the value for t_acc_info.tai_company
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiCompany(String taiCompany) {
        this.taiCompany = taiCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_url
     *
     * @return the value of t_acc_info.tai_url
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiUrl() {
        return taiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_url
     *
     * @param taiUrl the value for t_acc_info.tai_url
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiUrl(String taiUrl) {
        this.taiUrl = taiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_create_user
     *
     * @return the value of t_acc_info.tai_create_user
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiCreateUser() {
        return taiCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_create_user
     *
     * @param taiCreateUser the value for t_acc_info.tai_create_user
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiCreateUser(String taiCreateUser) {
        this.taiCreateUser = taiCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_create_time
     *
     * @return the value of t_acc_info.tai_create_time
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public Date getTaiCreateTime() {
        return taiCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_create_time
     *
     * @param taiCreateTime the value for t_acc_info.tai_create_time
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiCreateTime(Date taiCreateTime) {
        this.taiCreateTime = taiCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acc_info.tai_remark
     *
     * @return the value of t_acc_info.tai_remark
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public String getTaiRemark() {
        return taiRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acc_info.tai_remark
     *
     * @param taiRemark the value for t_acc_info.tai_remark
     *
     * @mbggenerated Fri Aug 25 10:43:24 CST 2017
     */
    public void setTaiRemark(String taiRemark) {
        this.taiRemark = taiRemark;
    }
}