package com.mc.model;

import java.util.Date;

public class TUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_id
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Integer tuiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_name
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_username
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_alias
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_email
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_phone
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_password
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_photo
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_create_time
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private Date tuiCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tui_remark
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    private String tuiRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_id
     *
     * @return the value of t_user_info.tui_id
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Integer getTuiId() {
        return tuiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_id
     *
     * @param tuiId the value for t_user_info.tui_id
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiId(Integer tuiId) {
        this.tuiId = tuiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_name
     *
     * @return the value of t_user_info.tui_name
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiName() {
        return tuiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_name
     *
     * @param tuiName the value for t_user_info.tui_name
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiName(String tuiName) {
        this.tuiName = tuiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_username
     *
     * @return the value of t_user_info.tui_username
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiUsername() {
        return tuiUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_username
     *
     * @param tuiUsername the value for t_user_info.tui_username
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiUsername(String tuiUsername) {
        this.tuiUsername = tuiUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_alias
     *
     * @return the value of t_user_info.tui_alias
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiAlias() {
        return tuiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_alias
     *
     * @param tuiAlias the value for t_user_info.tui_alias
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiAlias(String tuiAlias) {
        this.tuiAlias = tuiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_email
     *
     * @return the value of t_user_info.tui_email
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiEmail() {
        return tuiEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_email
     *
     * @param tuiEmail the value for t_user_info.tui_email
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiEmail(String tuiEmail) {
        this.tuiEmail = tuiEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_phone
     *
     * @return the value of t_user_info.tui_phone
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiPhone() {
        return tuiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_phone
     *
     * @param tuiPhone the value for t_user_info.tui_phone
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiPhone(String tuiPhone) {
        this.tuiPhone = tuiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_password
     *
     * @return the value of t_user_info.tui_password
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiPassword() {
        return tuiPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_password
     *
     * @param tuiPassword the value for t_user_info.tui_password
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiPassword(String tuiPassword) {
        this.tuiPassword = tuiPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_photo
     *
     * @return the value of t_user_info.tui_photo
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiPhoto() {
        return tuiPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_photo
     *
     * @param tuiPhoto the value for t_user_info.tui_photo
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiPhoto(String tuiPhoto) {
        this.tuiPhoto = tuiPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_create_time
     *
     * @return the value of t_user_info.tui_create_time
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public Date getTuiCreateTime() {
        return tuiCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_create_time
     *
     * @param tuiCreateTime the value for t_user_info.tui_create_time
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiCreateTime(Date tuiCreateTime) {
        this.tuiCreateTime = tuiCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tui_remark
     *
     * @return the value of t_user_info.tui_remark
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public String getTuiRemark() {
        return tuiRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tui_remark
     *
     * @param tuiRemark the value for t_user_info.tui_remark
     *
     * @mbggenerated Fri Aug 25 10:51:35 CST 2017
     */
    public void setTuiRemark(String tuiRemark) {
        this.tuiRemark = tuiRemark;
    }
}